#!/bin/bash

tgz=$1

yum install gcc-c++ -q -y
yum install make -q -y
yum install subversion -q -y
yum install quilt -q -y
if [ ! -f $tgz ]; then
        echo "fetching $tgz"
	wget -q http://download.qt.io/official_releases/qt/5.7/5.7.0/single/$tgz
fi

svn export https://github.com/mm-s/qtrac/trunk qtrac
wget http://dl.fedoraproject.org/pub/epel/7/x86_64/q/quilt-0.63-2.el7.noarch.rpm
yum install bzip2 diffstat procmail rpm-build -q -y
rpm -Uvh quilt-0.63-2.el7.noarch.rpm 
yum install quilt -q -y
yum install libX11-devel libXext-devel libXtst-devel libXrender -q -y


cd /usr/lib64
ln -s libXrender.so.1 libXrender.so
cd



dd if=/dev/zero of=/swapfile bs=1024 count=1000000
mkswap /swapfile
swapon /swapfile

echo "executing qtrac/bin/apply $tgz | tail -n1"

dir=`qtrac/bin/apply $tgz | tail -n1`
echo "entering $dir"
cd $dir


./configure -debug -silent -developer-build -opensource -confirm-license
time make

